import time
from datetime import datetime

def create_capsule():
    # 1. Capture Today's Date
    today_date = datetime.now().strftime("%A, %B %d, %Y")
    filename = "time_capsule_2026.txt"

    print(f"--- ✧ STARTING YOUR 2026 TIME CAPSULE ✧ ---")
    print(f"Today is {today_date}\n")

    # 2. The Questions (Listening to your specific requirements)
    questions = [
        ("FAVORITE SONG", "What is your current favorite song?"),
        ("BIGGEST GOAL", "What is your biggest goal right now?"),
        ("BEST FRIEND", "What is your best friend's name?"),
        ("CURRENT VIBE", "Describe your life right now in three words:"),
        ("MESSAGE", "What do you want to tell your future self?")
    ]

    answers = {}

    # 3. Interactive Input
    for key, prompt in questions:
        print(f"❯ {prompt}")
        ans = input("   Answer: ").strip()
        answers[key] = ans if ans else "N/A"

    # 4. Building the "Beautiful" Layout
    header_border = "★ " + ("=" * 45) + " ★"
    content = f"""
{header_border}
             LIFE ARCHIVE : 2026
{header_border}

DATE: {today_date}

[ THE SOUNDTRACK ]
  ♪ {answers['FAVORITE SONG']}

[ THE NORTH STAR ]
  🚀 {answers['BIGGEST GOAL']}

[ THE INNER CIRCLE ]
  🫂 {answers['BEST FRIEND']}

[ THE CURRENT STATE ]
  ✨ {answers['CURRENT VIBE']}

[ WORDS FOR LATER ]
  ✉️ "{answers['MESSAGE']}"

{header_border}
       Generated by your 2026 AI Collaborator.
{header_border}
"""

    # 5. Saving to the exact file you requested
    with open(filename, "w", encoding="utf-8") as f:
        f.write(content)

    print(f"\n✅ Done! I've saved your memories in '{filename}'.")

if __name__ == "__main__":
    create_capsule()
    